### ISSUE TITLE
Asked for apple id password multiple time even after the transaction was successful.

### ISSUE THREAD

**Issue by rohitgoyal** [chirag04/react-native-in-app-utils#55] opened 2016-12-15 10:45 UTC
Hi
The library work fine for enabling payments but it asks for the apple password again after the purchase has been completed. Sometimes the app ask me for password at the start up as well without invoking any payment function. 
I think this is related to lifecycle of SKPaymentQueue.
http://stackoverflow.com/questions/4988663/skpaymentqueue-addtransactionobserver-asking-for-app-store-password-on-startup-a

Can someone look at it?

**Comment by chirag04** [comment] 2016-12-15 14:45
duplicate of https://github.com/chirag04/react-native-in-app-utils/issues/46.

lets continue the discussion on that thread.

**Closed by chirag04** 2016-12-15 14:45 UTC
